# Generated by Django 5.1.4 on 2024-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="password",
        ),
        migrations.AlterField(
            model_name="register",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
