# Generated by Django 5.1.4 on 2024-12-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_remove_register_password_alter_register_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="register",
        ),
    ]
