# Generated by Django 5.1.4 on 2024-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="password",
            field=models.CharField(max_length=500),
        ),
    ]
