# Generated by Django 5.1.4 on 2024-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_alter_register_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="accountType",
            field=models.CharField(
                choices=[("B", "Business"), ("C", "Customer")],
                default="C",
                max_length=1,
            ),
        ),
    ]
