# Generated by Django 5.1.4 on 2024-12-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_register_accounttype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="accountType",
        ),
    ]
