# Generated by Django 5.1.4 on 2024-12-26 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sellerRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("dialCode", models.CharField(max_length=5)),
                (
                    "contact",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                    ),
                ),
                ("password", models.CharField(max_length=200)),
                (
                    "accountType",
                    models.CharField(
                        choices=[("B", "Business"), ("C", "Customer")],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("companyName", models.CharField(max_length=100)),
                ("storeName", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("B", "Business"), ("C", "Customer")],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
            ],
        ),
    ]
