# Generated by Django 5.1.4 on 2024-12-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellerRegistration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerregister",
            name="dialCode",
        ),
    ]
