# Generated by Django 5.1.4 on 2024-12-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellerRegistration", "0002_remove_sellerregister_dialcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="countryCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("dialCode", models.CharField(max_length=10)),
                ("image", models.CharField(max_length=100)),
            ],
        ),
    ]
